In [1]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import scipy.linalg
import random

# Major Topics From Chapters 3.1--4.3
This is a review for the second midterm. There will not be a full list of definitions and theorems recalled from the here, but will have a list of important concepts that you should know.



## Graph Concepts

Let $G = (V,E)$ be a graph.

You should know the following definitions:
* What is a graph?
* What does it mean for $G$ to be connected?
* What are connected components?
* What does it mean to be incident? What two objects in a graph can be incident?
* What does it mean for $G$ to be directed?
* What is the degree, out-degree, in-degree of a vertex?
* What is a path? a cycle?
* What does it mean for a graph to be weighted?


There are also several important matrices that are involved in a graph
$$
\begin{array}{|c|c|c|}\hline
\text{Undirected, unweighted} & \text{Undirected, weighted} & \text{Directed}\\\hline
a_{i,j} = \begin{cases}
1&: i\sim j\\
0&: \text{else}
\end{cases} &  a_{i,j} =\begin{cases}
w_{i,j}&: i\sim j\\
0&: \text{else}
\end{cases} & a_{i,j} =\begin{cases}
1&: i\in e_j\\
0&: \text{else}
\end{cases}
\\\hline
b_{i,j} = \begin{cases}
1&: i\in e_j\\
0&: \text{else}
\end{cases} &  --- & b_{i,j} =\begin{cases}
-1&: i\text{ soure of }e_j \\
+1&: i \text{ target of }e_j\\
0&: \text{else}
\end{cases}\\\hline
D = \text{diag}(A\boldsymbol{1}) & D = \text{diag}(A\boldsymbol{1}) & D = \text{diag}(A\boldsymbol{1}) \\\hline
L = D-A & L= D-A & ---\\ \hline
\mathcal{L} = D^{-1/2} L D^{-1/2} & \mathcal{L} = D^{-1/2} L D^{-1/2} &---\\\hline
P = D^{-1} A & P = D^{-1}A & P = D^{-1}A\\\hline
\end{array}
$$

Below is an example for a graph on $5$ vertices.

In [2]:
random.seed(100)
G = nx.binomial_graph(5, .6)


edges = [e for e in G.edges()]
nodes = [e for e in G.nodes()]
plt.figure(figsize = (9,6))

pos = nx.kamada_kawai_layout(G)
nx.draw(G, node_size = 1500, pos = pos, node_color = 'lightgrey', with_labels = True, labels = {nodes[j]:j+1 for j in range(len(nodes))},font_size = 25, width = 5)
plt.show()
A = nx.adjacency_matrix(G).toarray()
B = nx.incidence_matrix(G).toarray()
degs = np.matmul(A,[1 for _ in range(len(nodes))])
D = np.diag(degs)
P = np.matmul(np.linalg.inv(D),A)
L = D-A
normL = np.matmul(np.diag([x**(-1/2) for x in degs]), np.matmul(L,np.diag([x**(-1/2) for x in degs])))

print("A=")
print(A)
print("\n")

print("B=")
print(B)
print("\n")

print("L=")
print(L)
print("\n")
print("D=")
print(D)
print("\n")

print("P=")
print(np.round(P,2))
print("\n")

print("Normalized Laplacian=")
print(np.round(normL,2))
print("\n")


A=
[[0 1 1 0 0]
 [1 0 0 1 0]
 [1 0 0 1 1]
 [0 1 1 0 1]
 [0 0 1 1 0]]


B=
[[1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 1. 1.]]


L=
[[ 2 -1 -1  0  0]
 [-1  2  0 -1  0]
 [-1  0  3 -1 -1]
 [ 0 -1 -1  3 -1]
 [ 0  0 -1 -1  2]]


D=
[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 2]]


P=
[[0.   0.5  0.5  0.   0.  ]
 [0.5  0.   0.   0.5  0.  ]
 [0.33 0.   0.   0.33 0.33]
 [0.   0.33 0.33 0.   0.33]
 [0.   0.   0.5  0.5  0.  ]]


Normalized Laplacian=
[[ 1.   -0.5  -0.41  0.    0.  ]
 [-0.5   1.    0.   -0.41  0.  ]
 [-0.41  0.    1.   -0.33 -0.41]
 [ 0.   -0.41 -0.33  1.   -0.41]
 [ 0.    0.   -0.41 -0.41  1.  ]]




## Spectral Theorem
The matrices $L$ and $\mathcal{L}$ are **symmetric and positive semi-definite**. A key thing we learned about symmetric matrices $A\in \mathbb{R}^{d\times d}$ is the **spectral theorem**.

**Theorem** (Spectral Theorem): Suppose $A\in \mathbb{R}^{d\times d}$ is a symmetric matrix. Then there exists an orthonormal basis $\mathbf{v}_1,\dotsm,\mathbf{v}_d$ of eigenvectors: $A\mathbf{v}_j = \lambda_j \mathbf{v}_j$ for all $j$. Moreover, the matrix $A$ can be written as
$$
A = V \Lambda V^T = V \Lambda V^{-1} = \sum_{i=1}^d \lambda_i \mathbf{v}_i \mathbf{v}_i^T
$$
where 
$$
V = \begin{bmatrix}
|& |& & |\\
\mathbf{v}_1 &\mathbf{v}_2 & \dotsm &\mathbf{v}_d\\
|& |& & |
\end{bmatrix} \qquad \Lambda = \text{diag}(\lambda_1,\lambda_2,\dotsm,\lambda_d).
$$
Typically we have arranged the eigenvaleus $\lambda_1\ge \lambda_2\ge\dotsm\ge\lambda_d$.


### Courant-Fischer

There is also the Courant-Fischer theorem. I won't re-write this here. But you should be aware of what it says.

### Consequences for Graphs

We know that $\dim(\text{null}(L))\ge 1$. (Q: What vectors is in the null space?) Since $L$ is positive semi-definite, we have the spectral decomposition
$$
L = \sum_{i=1}^n \mu_i \mathbf{y}_i \mathbf{y}_i^T
$$
where $0 = \mu_1 \le \mu_2\le\dotsm\le \mu_n$. (Q: Why are all the eigenvalues non-negative?)

We proved (by a combination of results in class and on the homework):

**Lemma** The spectral decomposition for the Laplacian $L$ satisfies $\mu_k = 0$ but $\mu_{k+1}\neq 0$ if and only if $G$ has precisely $k$ many connected components. 



## Markov Chains

There are a lot of concepts in Markov chains that we talked about, so again I'll list some words/concepts that you should know how to define/what they are:

* What is a Markov chain? What is the Markov property?
* What is a state space?
* What is a transition matrix?
* What is a random walk on a graph?
* What is a stationary distribution?
* What does it mean for a Markov chain to be irreducible? aperiodic? weakly lazy?

Below are some results about (time-homogeneous) Markov chains that we learned.

Let $P\in \mathbb{R}^{n\times n}$ be the transition matrix for a Markov chain on $\{1,2,\dotsm,n\}$. Let 
$$
\boldsymbol{\mu} = \begin{bmatrix}
\mathbb{P}(X_0 = 1) & \mathbb{P}(X_0 = 2) & \dotsm &\mathbb{P}(X_0 = n)   
\end{bmatrix}
$$
be the distribution of $X_0$.

**Lemma** Under the above set-up:
$$
\mathbb{P}(X_t = j) = \left(\boldsymbol{\mu}P^t \right)_j
$$ is the $j^\text{th}$ entry of the row-vector $\boldsymbol{\mu}P^t$.

**Theorem** Every Markov chain on a finite state space has a stationary distribution. If the Markov chain is irreducible then stationary distribution is *unique* and, moreover, $\boldsymbol{\pi} = \begin{bmatrix} \pi_1&\pi_2&\dotsm& \pi_d\end{bmatrix}$ satisfies $\pi_j> 0$ for all $j$.

**Theorem** If a Markov chain is irreducible and aperiodic on a finite state space then as $t\to\infty$ 
$$
\left(\mathbf{\mu} P^t\right)_j \longrightarrow \pi_j
$$ for all $j$. Here $\boldsymbol{\pi}$ is the unique stationary distribution.

**Theorem** If a Markov chain $X$ is irreducible on a finite state space then
$$
\lim_{t\to\infty} \frac{1}{t} \sum_{s=1}^t 1_{[X_s = j]}  = \pi_j.
$$

## Markov Chains and Spectral Theorem

We saw that when we had a random walk on a weighted graph $G = (V,E,w)$ where $w$ are the weights that
$$
P = D^{-1/2} (I-\mathcal{L}) D^{1/2}
$$
(where we have added self-loops so that all the degrees are positive).

Since $\mathcal{L}$ is symmetric and positive semi-definite it has a spectral decomposition
$$
\mathcal{L} = Z H Z^T = ZHZ^{-1}\qquad Z = \begin{bmatrix} 
|&&|\\
\mathbf{z}_1 & \dotsm &\mathbf{z}_n\\
|&&|
\end{bmatrix} \qquad H = \text{diag}(\eta_1,\eta_2,\dotsm,\eta_n)
$$ where $\eta_1 = 0\le \eta_2\le\dotsm\le\eta_n\le 2$ (Q: Why is $\eta_n \le 2$?)

This gives $P$ a eigen-decomposition:
$$
P = \underset{M}{\underbrace{(D^{-1/2} Z)}}\underset{\Lambda}{\underbrace{ (I-H)}} \underset{M^{-1}}{\underbrace{(D^{-1/2}Z)^{-1}}}
$$
where $M\in \mathbb{R}^{n\times n}$ isa  matrix whose columns are eigenvectors of $P$ (Q: Why?) and $\Lambda$ is the diagonal matrix $\Lambda = \text{diag}(\lambda_1,\dotsm,\lambda_n)$ where $\lambda_1 = 1 - \eta_1 = 1$ and $\lambda_j = 1-\eta_j$. In particular, $|\lambda_j| \le 1$ for all $j$.

### Stationary distribution
A stationary distribution is
$$
\boldsymbol{\pi} = \frac{1}{{\sum_{j=1}^n \delta(j)}}  \begin{bmatrix}
 \delta(1) & \delta(2) &\dotsm& \delta(n)
 \end{bmatrix}.
$$

### Consequences when $P$ is irreducible and aperiodic
If $P$ is irreducible and aperiodic then $|\lambda_j|<1$ for all $j\neq 1$. (This is more detail than what we did in class).


Since $$Z(I-H) Z^{T} = \sum_{j=1}^n \lambda_j \mathbf{z}_j \mathbf{z}_j^T$$ (Q: Why?) we can write
$$
P = \sum_{j=1}^n \lambda_j  D^{-1/2} \mathbf{z}_j \mathbf{z}_j^T D^{1/2} = D^{-1/2}\mathbf{z}_1 \mathbf{z}_1^T  D^{1/2} + \sum_{j=2}^n \lambda_j D^{-1/2} \mathbf{z}_j \mathbf{z}_j^T D^{1/2}.
$$

Also $$
\mathbf{z}_1 = \begin{bmatrix}
\sqrt{\frac{\displaystyle \delta(1)}{\displaystyle \sum_{j=1}^n \delta(j)}}, \sqrt{\frac{\displaystyle \delta(2)}{\displaystyle \sum_{j=1}^n \delta(j)}}, \dotsm, \sqrt{\frac{\displaystyle \delta(n)}{\displaystyle \sum_{j=1}^n \delta(j)}}
\end{bmatrix}^T\\
= \frac{1}{\sqrt{\sum_{j=1}^n \delta(j)}}\begin{bmatrix} 
\sqrt{\delta(1)} & \sqrt{\delta(2)}&\dotsm & \sqrt{\delta(n)} 
\end{bmatrix}^T
$$
and so 
$$
D^{-1/2} \mathbf{z}_1 = D^{-1/2}\frac{1}{\sqrt{\sum_{j=1}^n \delta(j)}} \begin{bmatrix} 
\sqrt{\delta(1)} \\ \sqrt{\delta(2)}\\ \vdots \\ \sqrt{\delta(n)} 
\end{bmatrix} \\
= \frac{1}{\sqrt{\sum_{j=1}^n \delta(j)}} \begin{bmatrix}
\delta(1)^{-1/2} & 0 &\dotsm&0\\
0&\delta(2)^{-1/2} &\dotsm&0\\
\vdots&&\ddots& \vdots\\
0&\dotsm&0&\delta(n)^{1/2}
\end{bmatrix}
\begin{bmatrix} 
\sqrt{\delta(1)} \\ \sqrt{\delta(2)}\\\vdots \\ \sqrt{\delta(n)}
\end{bmatrix} = \frac{1}{\sqrt{\sum_{j=1}^n \delta(j)}} \boldsymbol{1}.
$$
and similarly
$$
 \mathbf{z}_1^T D^{1/2} =  \frac{1}{\sqrt{\sum_{j=1}^n \delta(j)}}  \begin{bmatrix}
 \delta(1) & \delta(2) &\dotsm& \delta(n)
 \end{bmatrix}.
$$

So
$$P = \boldsymbol{1}\boldsymbol{\pi} + \sum_{j=2}^n \lambda_j D^{-1/2} \mathbf{z}_j \mathbf{z}_j^T D^{1/2}
$$
where
$$
\boldsymbol{\pi} = \frac{1}{{\sum_{j=1}^n \delta(j)}}  \begin{bmatrix}
 \delta(1) & \delta(2) &\dotsm& \delta(n)
 \end{bmatrix}.
$$

So 
$$
\boldsymbol{\mu} P^t = \boldsymbol{\mu} \boldsymbol{1} \boldsymbol{\pi} + \sum_{j=2}^n \lambda_j^t \mathbf{w}_j
$$
where
$$
\mathbf{w}_j = \boldsymbol{\mu}  D^{-1/2} \mathbf{z}_j \mathbf{z}_j^T D^{1/2}.
$$
Since each $\lambda_j$ in the sum on the right-hand side is $|\lambda_j|<1$, we get for any (row) vector $\boldsymbol{\mu}$ such that $\sum_{j=1}^n \mu_j = 1$ (in particular for all probability vectors)
$$
\lim_{t\to\infty} \boldsymbol{\mu} P^t   = \boldsymbol{\mu} \boldsymbol{1} \boldsymbol{\pi}  = \boldsymbol{\pi}.
$$

# Chapter 4

There are some things in Chapter 4 that are also required to know. 
## Gradients and Hessian
Throughout we need $f:\mathbb{R}^d\to \mathbb{R}$ and we suppose that the derivatives below are defined.
The gradient is
$$
\nabla f(\mathbf{x}_0) = \begin{bmatrix}
\frac{\partial f}{\partial x_1}(\mathbf{x}_0)\\
\frac{\partial f}{\partial x_2}(\mathbf{x}_0)\\
\vdots\\
\frac{\partial f}{\partial x_d}(\mathbf{x}_0)
\end{bmatrix}
$$
and the Hessian 
$$
H_f( \mathbf{x}_0) = \begin{bmatrix}
\frac{\partial^2 f}{\partial x_1^2}(\mathbf{x}_0) & \frac{\partial^2 f}{\partial x_2\partial x_1}(\mathbf{x}_0)&\dotsm& \frac{\partial^2 f}{\partial x_d\partial x_1}(\mathbf{x}_0) \\
\frac{\partial^2 f}{\partial x_1 \partial x_2}(\mathbf{x}_0) & \frac{\partial^2 f}{\partial x_1\partial x_2}(\mathbf{x}_0)&\dotsm& \frac{\partial^2 f}{\partial x_d\partial x_2}(\mathbf{x}_0)\\
\vdots &&\ddots & \vdots\\
\frac{\partial^2 f}{\partial x_1\partial x_d}(\mathbf{x}_0) & \frac{\partial^2 f}{\partial x_2\partial x_d}(\mathbf{x}_0)&\dotsm& \frac{\partial^2 f}{\partial x_d^2}(\mathbf{x}_0)\\
\end{bmatrix}
$$


**Theorem** If $f$ is twice continuously differentiable (i.e. $\frac{\partial^2f}{\partial x_j\partial x_i}$ is continuous) then $H_f$ is symmetric.

You should also know the following definitions/concepts:
* Direction derivatives
* The chain rules
* Derivatives of $f(\mathbf{x}) = \mathbf{a}^T \mathbf{x}$ and $f(\mathbf{x}) = \langle\mathbf{x}, A\mathbf{x}\rangle$.

## Opitmality

You should also be able to define the following:
* Descent directions

You should know the following theorems, and why the first one is true. 


**Theorem** (First order necessary condition) Suppose that $f$ is continuously differentiable and $\mathbf{x}_0$ is a local minimum. Then $\nabla f(\mathbf{x}) = \boldsymbol{0}$.

The next result is now something you will know how to prove.

**Theorem** (Second order necessary condition and sufficient condition) Suppose that $f$ is twice continuously differentiable.

1) If $\mathbf{x}_0$ is a local minimum, then $\nabla f(\mathbf{x}_0) = \boldsymbol{0}$ and $H_f(\mathbf{x}_0)$ is positive semi-definite.

2)  If $\nabla f(\mathbf{x}_0) = \boldsymbol{0}$ and $H_f(\mathbf{x}_0)$ is positive definite, then $\mathbf{x}_0$ is a local minimum.